---
title: "OREB Modeling"
output:
  pdf_document: default
  html_document: default
date: "2026-03-08"
---



```{r}
library(dplyr)
library(tidyverse)
library(neuralnet)
library(forecast)
library(randomForest)
```


```{r}
cleandata <- read_csv("FINAL_MODEL_READY (2) - FINAL_MODEL_READY (2).csv")

```


```{r}
#Baseline Model
cleandata <- cleandata %>% mutate(year = year(ymd(game_date))) #creating new column for year
  
# Calculate the average from training seasons
train_mean <- mean(cleandata$oreb[cleandata$year <= 2025], na.rm = TRUE)

test_games <- cleandata %>% filter(year > 2025) #filtering test games as games after 2025

mae_baseline <- mean(abs(test_games$oreb - train_mean), na.rm = TRUE) #finding MAE using average as predicted value

cat("Baseline  MAE:", mae_baseline, "\n")

```


```{r}
#Linear Model 1


 #splitting older data into train and new data into test
train <- cleandata %>% filter(year <= 2025) %>% select(-home_team, -away_team, -game_id, -game_date, -spread, -total)
test  <- cleandata %>% filter(year > 2025)  %>% select(-home_team, -away_team, -game_id, -game_date, -spread, -total)

linearmodel <- lm(oreb ~ ., 
                  data = train) #training a model based on all possible predictors

sum_lin <- summary(linearmodel)

test$predicted_oreb <- predict(linearmodel, newdata = test) #finding predicted values for test data

mae <- mean(abs(test$oreb - test$predicted_oreb), na.rm = TRUE) #calculating MAE
cat("MAE:", mae, "\n")

sum_lin
```


```{r}
#Linear Model 2

linearmodel2 <- lm(oreb ~ home_back_to_back + efg_pct_diff + shooting_env5 + pace_pressure5 + free_throw_env5 + tov_env5 + expected_missed_fg + orb_per100_diff + drb_per100_diff + trb_per100_diff + expected_oreb_pressure + home_oreb_matchup + pace_rebound_pressure, #using predictors that are significant, and that i will know for future games
                  data = train) #training a model based on all possible predictors

summary(linearmodel2)

test$predicted_oreb2 <- predict(linearmodel2, newdata = test) #finding predicted values for test data

mae2 <- mean(abs(test$oreb - test$predicted_oreb2), na.rm = TRUE) #calculating MAE
cat("MAE:", mae2, "\n")
```

```{r}
#Simplified linear model


 #splitting older data into train and new data into test
train3 <- cleandata %>% filter(year <= 2025) %>% select(-home_team, -away_team, -game_id, -game_date, -spread, -total)
test3  <- cleandata %>% filter(year > 2025)  %>% select(-home_team, -away_team, -game_id, -game_date, -spread, -total)

linearmodel3 <- lm(oreb ~ free_throw_env5 + pace_pressure5 + expected_oreb_pressure + home_oreb_matchup + pace_rebound_pressure, 
                  data = train3) #training a model based on only the very most significant predictors

sum_lin3 <- summary(linearmodel3)

test3$predicted_oreb <- predict(linearmodel3, newdata = test3) #finding predicted values for test data

maesimple <- mean(abs(test3$oreb - test3$predicted_oreb), na.rm = TRUE) #calculating MAE
cat("MAE:", mae, "\n")

sum_lin3

```
```{r}
# Time series analysis - month

monthly <- cleandata %>% 
  mutate(month = floor_date(ymd(game_date), "month")) %>% #creating month column (saving each as the first day of the month)
  group_by(month) %>% #grouping by month
  summarise(avg_oreb = mean(oreb, na.rm = TRUE)) %>% #finding avg oreb per month
  arrange(month) %>% #arranging chronologically
  mutate(year = year(month)) 
#finding year from month column

ts_monthly <- ts(monthly$avg_oreb, frequency = 12) 
# Convert to ts object

# Train on 2025 and earlier, test on 2026
n_test   <- monthly %>% filter(year > 2025) %>% nrow()  # finding number of rows where year is over 2025
train_ts <- head(ts_monthly, length(ts_monthly) - n_test)  # training the model on only the rows not including the test rows


model_arima <- auto.arima(train_ts)               # creating time series model, needs ts object 
forecasted  <- forecast(model_arima, h = n_test)  # forecasted values based on model, needs a number 

# Build lookup table: month -> forecasted value
test_months <- monthly %>% filter(year > 2025) #creating new data frame with only test month
test_months$forecast_oreb <- as.numeric(forecasted$mean) #adding column for predicted monthly means

# Join forecast back to individual games
cleandata <- cleandata %>%
  mutate(month = floor_date(ymd(game_date), "month")) #saving month column as the date of the first day of that month, so it can be joined 

test_games <- cleandata %>%
  filter(year(ymd(game_date)) > 2025) %>%
  left_join(test_months %>% select(month, forecast_oreb), by = "month") 
#joining the forecasted monthly means to larger dataset

# MAE on individual games
mae_ts <- mean(abs(test_games$oreb - test_games$forecast_oreb), na.rm = TRUE)
cat("Time Series MAE (game level):", mae_ts, "\n")
```

```{r}
#Neural Net predictions
# Neural nets need scaled data (0 to 1 range), so I included features that have 0 to 1 range
features <- c("efg_pct_diff", "tov_pct_diff", "orb_pct_diff","ft_rate_diff", "shooting_env5", "free_throw_env5", "tov_env5", "x3pa_rate_pg_diff", "x3pa_rate_per100_diff", "last5_x3pa_rate_diff", "last10_x3pa_rate_diff")

# Remove rows with NAs in these columns
nn_data <- cleandata %>% 
  select(all_of(features), oreb, game_date, year) %>%
  na.omit()

# Scale oreb
oreb_min <- min(nn_data$oreb) #finding minimum oreb
oreb_max <- max(nn_data$oreb) #finding maximum oreb
nn_data$oreb_scaled <- (nn_data$oreb - oreb_min) / (oreb_max - oreb_min) #finding how far the oreb is above the minimum, over the range of possible orebs

# Chronological split
train_nn <- nn_data %>% filter(year <= 2025) %>% select(-game_date, -oreb) # removing oreb and date so they don't affect the model
test_nn  <- nn_data %>% filter(year >  2025) %>% select(-game_date, -oreb)

# Fit neural net 
model_nn <- neuralnet(oreb_scaled ~ efg_pct_diff + tov_pct_diff + orb_pct_diff + ft_rate_diff + shooting_env5 +  free_throw_env5 + tov_env5 + x3pa_rate_pg_diff + x3pa_rate_per100_diff + last5_x3pa_rate_diff + last10_x3pa_rate_diff,  #finding scaled oreb
                      data          = train_nn,
                      hidden        = c(4, 2),  # 2 hidden layers, 4 and 2 nodes
                      linear.output = TRUE)  # makes sure the output isn't between 0 and 1

# Predict then unscale back to real OREB values
pred_scaled <- predict(model_nn, test_nn %>% select(-oreb_scaled))
pred_oreb   <- pred_scaled * (oreb_max - oreb_min) + oreb_min # unscaling using oreb_min and oreb_max

# Unscale actual values too for fair comparison
actual_oreb <- test_nn$oreb_scaled * (oreb_max - oreb_min) + oreb_min

# MAE
mae_nn <- mean(abs(actual_oreb - pred_oreb), na.rm = TRUE)
cat("Neural Net MAE:", mae_nn, "\n")

```


```{r}
#hybrid model using time series

monthly_train <- monthly %>% filter(year <= 2025) #training months when year is less than 2025
monthly_test  <- monthly %>% filter(year > 2025) #test months when year is greater than 2025

n_test_ts <- nrow(monthly_test) #finding number of rows where year is greater than 2025
train_ts  <- head(ts_monthly, length(ts_monthly) - n_test_ts) # making ts object on just training rows

model_arima   <- auto.arima(train_ts) #fitting arima model
arima_fitted  <- as.numeric(model_arima$fitted)  # fitted values for training months
arima_forecast <- as.numeric(forecast(model_arima, h = n_test_ts)$mean)  # forecasts for test months

monthly_train$arima_oreb <- arima_fitted #adding values from model to training set
monthly_test$arima_oreb  <- arima_forecast #adding values from model to test set

#making lookup dataset with predictions by month
arima_lookup <- bind_rows(
  monthly_train %>% select(month, arima_oreb),
  monthly_test  %>% select(month, arima_oreb)
)

#joining predictions back to original dataset
cleandata2 <- cleandata %>%
  mutate(month = floor_date(ymd(game_date), "month")) %>%
  left_join(arima_lookup, by = "month")

#making chronological split of train and test data for my hybrid model
cleandata2 <- cleandata2 %>% mutate(year = year(ymd(game_date)))  
train_hybrid <- cleandata2 %>% filter(year <= 2025)
test_hybrid  <- cleandata2 %>% filter(year > 2025)

#fit hybrid model using arima forecast + best linear features
hybrid_model <- lm(oreb ~ arima_oreb + home_back_to_back + efg_pct_diff + shooting_env5 + pace_pressure5 + free_throw_env5 + tov_env5 + expected_missed_fg + orb_per100_diff + drb_per100_diff + trb_per100_diff + expected_oreb_pressure + home_oreb_matchup + pace_rebound_pressure, data = train_hybrid)
summary(hybrid_model)

#evaluating and finding MAE
test_hybrid$predicted_oreb <- predict(hybrid_model, newdata = test_hybrid)
mae_hybrid <- mean(abs(test_hybrid$oreb - test_hybrid$predicted_oreb), na.rm = TRUE)
cat("Hybrid MAE:", mae_hybrid, "\n")
```


```{r}
#Random Forest Model

# Same train/test split
train3 <- cleandata %>% filter(year <= 2025) %>% 
  select(-home_team, -away_team, -game_id, -game_date, -spread, -total) #eliminating variables that I won't have or will clog results like team names
test3  <- cleandata %>% filter(year > 2025)  %>% 
  select(-home_team, -away_team, -game_id, -game_date, -spread, -total)


train3_clean <- train3 %>% 
  select(oreb, home_back_to_back, efg_pct_diff, shooting_env5, pace_pressure5, free_throw_env5, tov_env5, expected_missed_fg, orb_per100_diff, drb_per100_diff, trb_per100_diff, expected_oreb_pressure, home_oreb_matchup, pace_rebound_pressure) %>% #selecting significant variables from second linear model
  drop_na() # Remove rows with NA in relevant columns (randomForest doesn't handle NA by default)

test3_clean <- test3 %>%
  select(oreb, home_back_to_back, efg_pct_diff, shooting_env5, pace_pressure5, free_throw_env5, tov_env5, expected_missed_fg, orb_per100_diff, drb_per100_diff, trb_per100_diff, expected_oreb_pressure, home_oreb_matchup, pace_rebound_pressure) %>%#same as with train data
  drop_na()

# Train random forest
rf_model <- randomForest(
  oreb ~ home_back_to_back + efg_pct_diff + shooting_env5 + pace_pressure5 + free_throw_env5 + tov_env5 + expected_missed_fg + orb_per100_diff + drb_per100_diff + trb_per100_diff + expected_oreb_pressure + home_oreb_matchup + pace_rebound_pressure,
  data      = train3_clean,
  ntree     = 500,       # number of trees
  mtry      = 4,         # predictors sampled at each split (default for regression = p/3)
  importance = TRUE      # allows variable importance plotting
)

# Predict and evaluate
test3_clean$predicted_oreb <- predict(rf_model, newdata = test3_clean)
mae_rf <- mean(abs(test3_clean$oreb - test3_clean$predicted_oreb), na.rm = TRUE)
cat("RF MAE:", mae_rf, "\n")

# Model summary
print(rf_model)

# Plotting variable importance
importance(rf_model)
```
```{r}
mae_rf <- mean(abs(test3_clean$oreb - test3_clean$predicted_oreb), na.rm = TRUE)
cat("RF MAE:", mae_rf, "\n")
```


```{r}
#Linear model using just expected_oreb_pressure
# Train/test split
train4 <- cleandata %>% filter(year <= 2025) %>% 
  select(-home_team, -away_team, -game_id, -game_date, -spread, -total)
test4  <- cleandata %>% filter(year > 2025)  %>% 
  select(-home_team, -away_team, -game_id, -game_date, -spread, -total)

linearmodelone <- lm(oreb ~ expected_oreb_pressure, data = train4) # train4, not train3

sum_linone <- summary(linearmodelone)

# exp() to back-transform from log scale to original oreb scale
test4$predicted_oreb <- predict(linearmodelone, newdata = test4)

mae_one <- mean(abs(test4$oreb - test4$predicted_oreb), na.rm = TRUE)
cat("One variable MAE:", mae_one, "\n")
sum_linone
```
